set nocompatible
filetype on
filetype plugin on
filetype indent on

syntax on

""" GENERAL SETTINGS {{{
colorscheme slate
set foldmethod=syntax
set relativenumber
set shiftwidth=4
set tabstop=4
set expandtab
set nobackup
set scrolloff=10
set nowrap
set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set showmatch
set hlsearch
set history=1000
set mouse=a
set ttymouse=xterm2

set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
""" }}}

""" PLUGINS {{{
call plug#begin('./plugged')

Plug 'tpope/vim-fugitive'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()
""" }}}

""" KEYBINDS {{{

noremap <Leader>f :Files<CR>
noremap <Leader>gf :GFiles<CR>

""" }}}
